---
title: "DATA 607 Final Project - MongoDB Test Queries"
author: "Jason Givens-Doyle, Romerl Elizes & Soumya Ghosh"
date: "December 12, 2018"
output: 
  html_document: 
    toc: true
    df_print: kable
    theme: cerulean
    highlight: pygments
    css: ./lab.css
  #  code_folding:hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(RODBC)
library(mongolite)
library(knitr)
library(kableExtra)
library(stringr)
library(dplyr)
library(tidyr)
library(scales)
library(ggplot2)
library(plotly)
library(maps)
library(mapdata)
library(ggrepel) #not using this at the moment, but it does give the option to add labels.  While not useful for the 

options(knitr.table.format = "html")
```


```{r connect-to-mongodatabase, eval=TRUE}
mbreast <- mongo("breast")
mdigothr <- mongo("digothr")
mmalegen <- mongo("malegen")
mfemgen <- mongo("femgent")
mother <- mongo("other")
mrespir <- mongo("respir")
mcolrect <- mongo("colrect")
mlymyleuk <- mongo("lymyleuk")
murinary <- mongo("urinary")

```

```{r test1}
# Perform Test Queries for each Table
breastDF <- mbreast$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
breastDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test2}
# Perform Test Queries for each Table
digothrDF <- mdigothr$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
digothrDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test3}
# Perform Test Queries for each Table
malegenDF <- mmalegen$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
malegenDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test4}
# Perform Test Queries for each Table
femgenDF <- mfemgen$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
femgenDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test5}
# Perform Test Queries for each Table
otherDF <- mother$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
otherDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test6}
# Perform Test Queries for each Table
respirDF <- mrespir$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
respirDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test7}
# Perform Test Queries for each Table
colrectDF <- mcolrect$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
colrectDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test8}
# Perform Test Queries for each Table
lymyleukDF <- mlymyleuk$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
lymyleukDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```

```{r test9}
# Perform Test Queries for each Table
urinaryDF <- murinary$find( query = '{"race" : "White", "birthYear" : { "$gt" : 1960 } }', fields = '{}', limit = 25 )
urinaryDF %>% 
  kable () %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width="100%",height="300px")
```
